export default [
  {
    img: 'card-app.png',
    product: 'Facebook',
    name: 'Mark',
    icon1: 'fa-star',
    icon2: 'fa-star',
    icon3: 'fa-star',
  },
  {
    img: 'card-app.png',
    product: 'Facebook',
    name: 'Mark',
    icon1: 'fa-star',
    icon2: 'fa-star',
    icon3: 'fa-star',
  },
  {
    img: 'card-app.png',
    product: 'Facebook',
    name: 'Mark',
    icon1: 'fa-star',
    icon2: 'fa-star',
    icon3: 'fa-star',
  },
  {
    img: 'card-app.png',
    product: 'Facebook',
    name: 'Mark',
    icon1: 'fa-star',
    icon2: 'fa-star',
    icon3: 'fa-star',
  },
  {
    img: 'card-app.png',
    product: 'Facebook',
    name: 'Mark',
    icon1: 'fa-star',
    icon2: 'fa-star',
    icon3: 'fa-star',
  },
  {
    img: 'card-app.png',
    product: 'Facebook',
    name: 'Mark',
    icon1: 'fa-star',
    icon2: 'fa-star',
    icon3: 'fa-star',
  },
  {
    img: 'card-app.png',
    product: 'Facebook',
    name: 'Mark',
    icon1: 'fa-star',
    icon2: 'fa-star',
    icon3: 'fa-star',
  },
  {
    img: 'card-app.png',
    product: 'Facebook',
    name: 'Mark',
    icon1: 'fa-star',
    icon2: 'fa-star',
    icon3: 'fa-star',
  },
];
